# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Log_W_bar <- function(zbar, theta, Oz2, gamma) {
    .Call('phenoecosim_Log_W_bar', PACKAGE = 'phenoecosim', zbar, theta, Oz2, gamma)
}

W_bar <- function(zbar, theta, Oz2, gamma, LOG) {
    .Call('phenoecosim_W_bar', PACKAGE = 'phenoecosim', zbar, theta, Oz2, gamma, LOG)
}

R_bar <- function(N, R0, Wbar, K, thetaL) {
    .Call('phenoecosim_R_bar', PACKAGE = 'phenoecosim', N, R0, Wbar, K, thetaL)
}

Log_R_bar <- function(N, R0, logWbar, K, thetaL) {
    .Call('phenoecosim_Log_R_bar', PACKAGE = 'phenoecosim', N, R0, logWbar, K, thetaL)
}

Beta <- function(gamma, A, B, a, b, e_t, e_plast) {
    .Call('phenoecosim_Beta', PACKAGE = 'phenoecosim', gamma, A, B, a, b, e_t, e_plast)
}

Va <- function(env, GG) {
    .Call('phenoecosim_Va', PACKAGE = 'phenoecosim', env, GG)
}

Env_shift <- function(t, env_args) {
    .Call('phenoecosim_Env_shift', PACKAGE = 'phenoecosim', t, env_args)
}

pdLande <- function(t, X, params, G, env_args) {
    .Call('phenoecosim_pdLande', PACKAGE = 'phenoecosim', t, X, params, G, env_args)
}

