# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute mean fitness under stabilizing selection
#' @param zbar mean trait prior to selection
#' @param theta enironmental optimum
#' @param Oz2 strength of stabilizing selection
#' @param gamma 1/(Oz2 + Vz2), with Vz2 phenotypic variance 
#' @details no details
#' @export
Log_W_bar <- function(zbar, theta, Oz2, gamma) {
    .Call('phenoecosim_Log_W_bar', PACKAGE = 'phenoecosim', zbar, theta, Oz2, gamma)
}

#' Compute mean fitness under stabilizing selection
#' @inheritParams Log_W_bar
#' @param LOG (=TRUE) whether to return the log of fitness  
#' @details no details
#' @export
W_bar <- function(zbar, theta, Oz2, gamma, LOG) {
    .Call('phenoecosim_W_bar', PACKAGE = 'phenoecosim', zbar, theta, Oz2, gamma, LOG)
}

#' Compute population growth rate under stabilizing selection
#' @param N number of individuals in this generation
#' @param R0 basic reproductive number
#' @param Wbar average fitness
#' @param K carrying capacity
#' @param thetaL theta-logistic parameter for density dependence
#' @details Assumes theta-logistic population regulation
#' would be good to have separate DD function specified after
#' chevin and lande 2010
#' @export
R_bar <- function(N, R0, Wbar, K, thetaL) {
    .Call('phenoecosim_R_bar', PACKAGE = 'phenoecosim', N, R0, Wbar, K, thetaL)
}

#' Compute LOG population growth rate under stabilizing selection
#' @inheritParams R_bar
#' @param logWbar log average fitness
#' @details Assumes theta-logistic population regulation
#' would be good to have separate DD function specified after
#' chevin and lande 2010
#' @export
Log_R_bar <- function(N, R0, logWbar, K, thetaL) {
    .Call('phenoecosim_Log_R_bar', PACKAGE = 'phenoecosim', N, R0, logWbar, K, thetaL)
}

#' Selection on plasticity as as function of environment assuming stabilizing selection
#' @param gamma = 1/(Oz2 + Vz2), with Vz2 phenotypic variance
#' @param A the environmental optimum RN int
#' @param B the environmental optimum RN slope
#' @param a current value of RN int
#' @param b current value of RN slope
#' @param e_t environment now
#' @param e_plast env that cues plasticity
#' @export
Beta <- function(gamma, A, B, a, b, e_t, e_plast) {
    .Call('phenoecosim_Beta', PACKAGE = 'phenoecosim', gamma, A, B, a, b, e_t, e_plast)
}

#' Va additive genetic variance in the phenotype as a function of the environment
#' @param env environment in which plastiicty is cued
#' @param GG additive genetic variance-covariance matrix
#' @export
Va <- function(env, GG) {
    .Call('phenoecosim_Va', PACKAGE = 'phenoecosim', env, GG)
}

#' Compute a white noise environment with a shift
#' @param t the time point
#' @param env_args other args:
#' t.jump the location for the jump,
#' delta env change that takes place at t.jump
#' sd noise in env
#' sdc noise in cue
#' @details nada
#' @export
Env_shift_cpp <- function(t, env_args) {
    .Call('phenoecosim_Env_shift_cpp', PACKAGE = 'phenoecosim', t, env_args)
}

#' Internal function
pdIter <- function(len, z_bar, theta_t, Oz2, gamma, A, B, a, b, e_t, e_plast, G, logN, R0, K, thetaL) {
    .Call('phenoecosim_pdIter', PACKAGE = 'phenoecosim', len, z_bar, theta_t, Oz2, gamma, A, B, a, b, e_t, e_plast, G, logN, R0, K, thetaL)
}

#' Compute change in fitness over one generation after stabilizing selection
#' function of environment (after Lande Chevin)
#' @param t timestep
#' @param X parameters (a, b, env, logN)
#' @param params a list with (Oz2, AB, R0, K, theta)
#' @param G the (constant) G matrix
#' @param env_args extra args for env.fn
#' @details function signature as for use with deSolve
#' imposes fitness based on Lande
#' and demography after CL 2010
#' @return rowvector: log R bar, delta R bar, variance load
#' @export
pdRespVarLoad <- function(t, X, params, G, env_args) {
    .Call('phenoecosim_pdRespVarLoad', PACKAGE = 'phenoecosim', t, X, params, G, env_args)
}

#' Compute trait + demographic change over one generation under stabilizing selection as 
#' function of environment (after Lande Chevin)
#' @param t timestep
#' @param X parameters (a, b, env, logN)
#' @param params a list with (Oz2, AB, R0, K, theta)
#' @param G the (constant) G matrix
#' @param env_args extra args for env.fn
#' @details function signature as for use with deSolve
#' imposes fitness based on Lande
#' and demography after CL 2010
#' @export
pdLande <- function(t, X, params, G, env_args) {
    .Call('phenoecosim_pdLande', PACKAGE = 'phenoecosim', t, X, params, G, env_args)
}

#' Compute trait + demographic change over T generations under stabilizing selection as 
#' function of environment (after Lande Chevin)
#' @param T end time, assuming start time of 1
#' @param X parameters (a, b, env, logN)
#' @param params a list with (Oz2, AB, R0, K, theta)
#' @param G the (constant) G matrix
#' @param env_args extra args for env.fn
#' @details function signature as for use with deSolve
#' imposes fitness based on Lande
#' and demography after CL 2010
#' @export
pdLandeT <- function(T, X, params, G, env_args) {
    .Call('phenoecosim_pdLandeT', PACKAGE = 'phenoecosim', T, X, params, G, env_args)
}

